"""baseline: organizations, departments, users

Revision ID: 6d7db949fc2d
Revises: 
Create Date: 2026-07-30 15:35:38.992729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '6d7db949fc2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('NEWID()'), nullable=False),
    sa.Column('name', sa.NVARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('NEWID()'), nullable=False),
    sa.Column('org_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('name', sa.NVARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('NEWID()'), nullable=False),
    sa.Column('org_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('department_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('email', sa.NVARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.NVARCHAR(length=255), nullable=False),
    sa.Column('name', sa.NVARCHAR(length=255), nullable=False),
    sa.Column('role', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.CheckConstraint("(role = 'org_admin' AND department_id IS NULL) OR (role IN ('dep_admin', 'member') AND department_id IS NOT NULL)", name='CHK_role_dept_consistency'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('departments')
    op.drop_table('organizations')
    # ### end Alembic commands ###
